app/src/config/routes.rb
Rails.application.routes.draw do

  concern :sluggable do
    collection do
      get 'slug'
    end
  end

  concern :commentable do
    member do
      post 'comment'
    end
  end

  resources :tags, only: :index do
    get :autocomplete, on: :collection
  end

  get 'ssearch' => "ssearch#index"

  resources :slides

  resources :contests, path: 'premio', concerns: :sluggable, except: [:show, :toggle_instagram_image,:index]
  get 'premio/:title/:image_id', to: 'contests#preview_instagram_image', as: :contest_image
  get 'premio/:title', to: 'contests#show', as: :show_contest
  get 'premio', to: 'contests#show'
  get 'contests/toggle_instagram_image/:image_id', to: 'contests#toggle_instagram_image'
  get 'contests', to: 'contests#index'

  resources :events, path: 'eventos', concerns: :sluggable

  resources :resorts, path: 'estacoes-ski-snowboard', concerns: :sluggable, except: :show

  get '/resorts/:id', to: 'resorts#resort_redirect', as: :resort_redirect
  get 'estacoes-ski-snowboard/:relation_id/:id', to: 'resorts#show', as: :show_resort

  get 'estacoes-ski-snowboard/:id', to: 'resort_categories#show', as: :show_resort_category
  resources :resort_categories, concerns: :sluggable, except: :show do
    get 'children', on: :member
  end

  get '/resorts', to: redirect('/estacoes-ski-snowboard')
  get '/resort_categories/:id', to: redirect('/estacoes-ski-snowboard/%{id}')

  resources :blogs

  resources :tips, path: 'dicas-de-snowboard', concerns: [:sluggable, :commentable], except: :show

  get '/tips/:id', to: 'tips#tip_redirect', as: :tip_redirect
  get 'dicas-de-snowboard/:category_id/:id', to: 'tips#show', as: :show_tip
  get 'dicas/:category_id/:id', to: redirect('tips#show')

  get 'dicas-de-snowboard/:id', to: 'tip_categories#show', as: :show_tip_category
  get 'dicas/:id', to: redirect('tip_categories#show')

  resources :tip_categories, concerns: :sluggable, except: :show
  get '/tips', to: redirect('/dicas-de-snowboard')
  get '/dicas', to: redirect('/dicas-de-snowboard')
  get '/tip_categories/:id', to: redirect('/dicas-de-snowboard/%{id}')

  resources :videos,  path: 'snowboard-videos', concerns: :sluggable, except: :show
  get 'snowboard-videos/:relation_id/:id', to: 'videos#show', as: :show_video

  get 'snowboard-videos/:id', to: 'video_categories#show', as: :show_video_category
  resources :video_categories, concerns: :sluggable, except: :show

  get '/video_categories/:id', to: redirect('/videos/%{id}')

  resources :breezes, :breeze_categories
  resources :image_galleries, :media_image_categories

  resources :accommodations, :tour_styles

  resources :tours, path: '/vamo-junto-snowboard', except: :show do
    get ':resort_country_id/:id', to: 'tours#show', as: :show_tour, on: :collection
    get 'search', on: :collection
    get ':slug', to: 'tours#index', on: :collection
    post 'comment', on: :member
    scope module: 'tours' do
      resources :participants do
        get 'recall', on: :member
      end
    end
  end
  resources :offers, path: '/pacotes-ski-snowboard', except: :show do
    get ':resort_country_id/:id', to: 'offers#show', as: :show_offer, on: :collection
    get 'search', on: :collection
    get ':slug', to: 'offers#index', on: :collection
    scope module: 'offers' do
      resources :participants
    end
  end

  root 'static_pages#index'

  get '/galera', to: 'static_pages#galera', path: '/contatos'
  get '/friends', to: 'static_pages#friends', path: '/amigos'
  get '/places', to: 'static_pages#places', path: '/lugares'
  get '/stickers', to: 'static_pages#stickers', path: '/adesivos'

  get 'users_controller/finish_signup'

  get '/discourse/sso', to: 'discourse#sso'
  get '/discourse/after_sign_in', to: 'discourse#after_sign_in'
  get '/discourse/logout', to: 'discourse#logout'

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    scope module: 'users' do
      resources :tours
      resources :offers
    end
  end
  scope '/manage' do
    resources :users do
      resources :image_galleries
      resources :notifications
      patch 'update_password', on: :collection
      resources :tours, module: 'manage'
    end
  end
  namespace :manage do
    resources :tours, concerns: :sluggable do
      scope module: 'tours' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end
    resources :offers, concerns: :sluggable do
      scope module: 'offers' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end

    resources :tags
  end

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/user' => 'users#profile', via: [:get], :as => :profile
  match '/user/full_sign_out' => 'users#full_sign_out', via: [:get], :as => :full_sign_out
  match '/athletes' => 'users#athletes', via: [:get], :as => :athletes, path: 'atletas-de-snowboard'
  match '/agencies' => 'offers#agencies', via: [:get], :as => :agencies, path: 'agencias-ski-snowboard'
  match '/organizations' => 'users#organizations', via: [:get], :as => :organizations, path: 'ogranizacoes-de-snowboard'

  get '/galera', to: redirect('contatos')
  get '/friends', to: redirect('amigos')
  get '/tours', to: redirect('vamo-junto-snowboard')
  get '/offers', to: redirect('pacotes-ski-snowboard')
  get '/athletes', to: redirect('atletas-de-snowboard')
  get '/agencies', to: redirect('agencias-ski-snowboard')
  get '/organizations', to: redirect('ogranizacoes-de-snowboard')

end

app/src/app/models/video_category.rb
# create_table :video_categories, force: true do |t|
#   t.string    :name
#   t.text      :description
#   t.string    :ancestry
#   t.string    :index
#   t.integer   :ancestry_depth,               default: 0
#   t.timestamp :created_at,     precision: 6
#   t.timestamp :updated_at,     precision: 6
#   t.string    :image
#   t.string    :slug
# end

class VideoCategory < ActiveRecord::Base
  include Slug
  slugged :name

  has_ancestry( :cache_depth => true )
  has_many :videos

  validates :name, presence: true
  mount_uploader :image, CategoryImageUploader


  def videos_size_with_children
    videos.size + children.inject(0) {|sum, child| sum + child.videos_size_with_children }
  end


end

app/src/app/controllers/video_categories_controller.rb
class VideoCategoriesController < ApplicationController
  authorize_resource
  load_resource expect: :show

  before_action :load_show_resource, only: :show
  before_action :set_froala_config

  # GET /video_categories
  # GET /video_categories.json
  def index
    @video_categories = VideoCategory.all
  end

  # GET /video_categories/1
  # GET /video_categories/1.json
  def show
    @videos = @video_category.videos.sort_by { |a| [ a.created_at ] }.reverse
    #.page(params[:page])
  end

  # GET /video_categories/new
  def new
    @video_category = VideoCategory.new
  end

  # GET /video_categories/1/edit
  def edit
  end

  def slug
    video_category = VideoCategory.new name: params[:title]
    render json: { slug: video_category.slug_preview }
  end

  # POST /video_categories
  # POST /video_categories.json
  def create
    @video_category = VideoCategory.new(video_category_params)

    respond_to do |format|
      if @video_category.save
        format.html { redirect_to show_video_category_path(@video_category), notice: 'Video category was successfully created.' }
        format.json { render :show, status: :created, location: @video_category }
      else
        format.html { render :new }
        format.json { render json: @video_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_categories/1
  # PATCH/PUT /video_categories/1.json
  def update
    respond_to do |format|
      if @video_category.update(video_category_params)
        format.html { redirect_to show_video_category_path(@video_category), notice: 'Video category was successfully updated.' }
        format.json { render :show, status: :ok, location: @video_category }
      else
        format.html { render :edit }
        format.json { render json: @video_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_categories/1
  # DELETE /video_categories/1.json
  def destroy
    @video_category.destroy
    respond_to do |format|
      format.html { redirect_to video_categories_url, notice: 'Video category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def video_category_params
    params.require(:video_category).permit(:name, :slug, :parent_id, :description, :image)
  end
end

app/src/app/helpers/video_categories_helper.rb
module VideoCategoriesHelper
  include TipCategoriesHelper
  def menu_video_categories(video_categories)
    video_categories.map do |video_category, sub_video_categories|
      if sub_video_categories.empty?
        content_tag(:li, link_to(video_category.name, show_video_category_path(video_category)))
      else
        content_tag(:li, link_to(video_category.name, "#" ) + content_tag(:ul, sub_menu_video_categories(sub_video_categories),:class => 'subsubmenu'),:class => 'subsubmenu-item')
      end

    end.join.html_safe
  end

  def sub_menu_video_categories(video_categories)
    video_categories.map do |video_category, sub_video_category|
      content_tag(:li,link_to(video_category.name, show_video_category_path(video_category)))
    end.join.html_safe
  end

end

app/src/app/views/video_categories/_form.html.haml
= form_for @video_category do |f|
  - if @video_category.errors.any?
    #error_explanation
      %h1= "#{pluralize(@video_category.errors.count, "error")} prohibited this video_category from being saved:"
      %ul
        - @video_category.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name, data: { url: slug_video_categories_path }
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :parent_id, t('parent')
    = f.collection_select(:parent_id, VideoCategory.all,:id, :name,{:prompt => t('selectParent')})
  .field
    = f.label :description
    = f.text_area :description, class: 'froala', :rows => 40, :cols => 120
  .field
    = image_tag @video_category.image_url(:thumb_1200_630).to_s
    = f.label :image
    = f.file_field :image
    = f.check_box :remove_image

  .actions
    = f.submit 'Save'

app/src/app/views/video_categories/_video_category.html.haml
%li.video_category
  .details
    %p.name= video_category.name
    %p= truncate( video_category.description.html_safe, length: 200)
  .clear
  - if can? :video_category, :update, :destroy
    .control
      = link_to t('edit'), edit_video_category_path(video_category)
      = link_to 'Destroy', video_category, method: :delete, data: { confirm: 'Are you sure?' }

app/src/app/views/video_categories/edit.html.haml
%h2 Editing video_category

= render 'form'

= link_to 'Show', @video_category
\|
= link_to 'Back', video_categories_path

app/src/app/views/video_categories/index.html.haml
.main-content
  .heading
  -if can? VideoCategory, :create
    = link_to 'New video category', new_video_category_path
  .clear
  %ul.video_category_list
    =nested_categories @video_categories.arrange
.clear

app/src/app/views/video_categories/new.html.haml
%h1=t('newvideoCategory')

= render 'form'

= link_to 'Back', video_categories_path

app/src/app/views/video_categories/show.html.haml
%p#notice= notice
.main-content{:itemscope => true, :itemtype => "http://schema.org/Article"}
  -content_for :for_head do
    %title Videos de Snowboard: #{@video_category.name.to_s} | Zona Radical
    %meta{:name => "description", :content => strip_tags(@video_category.description.to_s)}
    %meta{:name=>"keywords", :content => "videos de snowboard, video aulas, como aprender snowboard, snowboard no Brasil"}
    -# facebook METAS
    %meta{:property=>"og:type", :content =>"website"}
    %meta{:property=>"og:title", :content => "Videos de Snowboard: "+@video_category.name.to_s+" | Zona Radical"}
    %meta{:property=>"og:description", :content => strip_tags(@video_category.description.to_s)}
    %meta{:property=>"og:url", :content => request.original_url.to_s}
    %meta{:property=>"og:image", :content =>@video_category.image_url(:thumb_1200_630).to_s}
    -# Microdata Metas
    %meta{:itemprop=>"author", :content =>"Zona Radical"}
    %meta{:itemprop=>"description", :content =>  strip_tags(@video_category.description.to_s)}
    %meta{:itemprop=>"keywords", :content => "videos de snowboard, video aulas, como aprender snowboard, snowboard no Brasil"}
    %meta{:itemprop=>"url", :content => request.original_url.to_s}
    %meta{:itemprop=>"headline", :content => "Video de snowboard em portugues do Brasil"}
    %meta{:itemprop=>"image", :content=> @video_category.image_url(:thumb_1200_630).to_s}
  .heading
    %h1{:itemprop=>"name"}
      -if @video_category.ancestry
        -#= link_to "Videos", "/videos/videos/", :class=>'video-header'
        />>
        - nums=Array.new(@video_category.ancestry_depth-1)
        - nums[0]=@video_category
        - (1..nums[0].ancestry_depth).each do |i|
          - nums[i]=nums[i-1].parent
        = nums.reverse.map{|wl| link_to wl.name, show_video_category_path(wl), :class=>'video-header'}.join(' >> ').html_safe
      -else
        =@video_category.name

  .introtext{:itemprop=>"description"}
    = @video_category.description.html_safe unless @video_category.description.nil?
    %meta{:itemprop=>"datePublished", :content=> @video_category.updated_at}
  -if can? :update, @video_category
    = link_to t('edit'), edit_video_category_path(@video_category)
  .clear
  %ul.stations-list
    =render @videos
    -#= will_paginate @videos,:previous_label => '<<',:next_label => '>>', :inner_window => 1
  -if @video_category.children?
    -@video_category.children.each do |video_sub_category|
      -unless video_sub_category.videos_size_with_children==0
        .heading
          %h1= video_sub_category.name + ' (' + video_sub_category.videos_size_with_children.to_s + ')'
          -if video_sub_category.videos_size_with_children > 4
            = link_to t('allVideos') + video_sub_category.name,  show_video_category_path(video_sub_category), class: :all
        .introtext= video_sub_category.description.html_safe unless video_sub_category.description.nil?
        -if can? :update, video_sub_category
          = link_to t('edit'), edit_video_category_path(video_sub_category)
        .clear
        %ul.stations-list
          =render video_sub_category.videos.sort_by { |a| [ a.created_at ] }.reverse[0..3]
        -if video_sub_category.videos_size_with_children > 4
          %p.others
            = link_to t('otherVideos') + video_sub_category.name, show_video_category_path(video_sub_category)
      -if video_sub_category.children?
        -video_sub_category.children.each do |video_subsub_category|
          -unless video_subsub_category.videos_size_with_children==0
            .heading
              %h1= video_subsub_category.name + ' (' + video_subsub_category.videos_size_with_children.to_s + ')'
              -if video_subsub_category.videos_size_with_children > 4
                = link_to t('allVideos') + video_subsub_category.name,  show_video_category_path(video_subsub_category), class: :all
            .introtext= video_subsub_category.description.html_safe unless video_subsub_category.description.nil?
            -if can? :update, video_subsub_category
              = link_to t('edit'), edit_video_category_path(video_subsub_category)
            .clear
            %ul.stations-list
              =render video_subsub_category.videos.sort_by { |a| [ a.created_at ] }.reverse[0..3]
            -if video_subsub_category.videos_size_with_children > 4
              %p.others
                = link_to t('otherVideos') + video_subsub_category.name, show_video_category_path(video_subsub_category)
-content_for :aside do
  %aside
    =render 'shared/aside/aside_social_buttons'
    =#render 'shared/aside/aside_video_category', :video_category => @video_category
    =render 'shared/aside/aside_advert'
    =render 'shared/aside/aside_fb_like_box'
    =render 'shared/aside/aside_resort_gallery'
  .clear


-content_for :for_mobile do
  -if @video_category.parent
    =render 'layouts/header_xs', :header_txt=> @video_category.parent.name, :header_url => show_video_category_path(@video_category.parent)
  -else
    =render 'layouts/header_xs', :header_txt=> t('All Videos'), :header_url => main_app.videos_path

  .container
    .articles
      -#=render 'layouts/list_filters_xs', :header_txt => @tip_category.name
      .articles--title.clearfix
        .articles--filter.left
          %a.articles--filter-btn{:href => "#"} Categorias
          .articles--filter-box
            %ul.articles--filter-list
              =sub_menu_video_categories VideoCategory.all

        .news--item-title.right.clearfix
          .news--item-name.left
            =@video_category.name


      - if @video_category.description.present?
        .article
          .article--inner
            .article--desc
              = @video_category.description.html_safe

      = render partial: "videos/video_xs", collection: @videos
      -#= will_paginate @videos

      -#-if @video_category.children?
      -@video_category.children.each do |video_sub_category|
        -if video_sub_category.videos
          .articles--title.clearfix
            .news--item-title.right.clearfix
              .news--item-name.left
                =video_sub_category.name
          = render partial: "videos/video_xs", collection: video_sub_category.videos.sort_by { |a| [ a.created_at ] }.reverse[0..3]
          -if video_sub_category.videos.count > 4
            %p.others
              = link_to t('otherVideos') + video_sub_category.name, show_video_category_path(video_sub_category)
        -video_sub_category.children.each do |video_subsub_category|
          -if video_subsub_category.videos_size_with_children>0
            .articles--title.clearfix
              .news--item-title.right.clearfix
                .news--item-name.left
                  =video_sub_category.name+':'
                  =video_subsub_category.name
            = render partial: "videos/video_xs", collection: video_subsub_category.videos.sort_by { |a| [ a.created_at ] }.reverse[0..3]
            -if video_subsub_category.videos_size_with_children > 4
              %p.others
                = link_to t('otherVideos') + video_subsub_category.name, show_video_category_path(video_subsub_category)
          -else
            .articles--title.clearfix
              .news--item-title.right.clearfix
                .news--item-name.left
                  =video_sub_category.name
            = render partial: "videos/video_xs", collection: video_sub_category.videos.sort_by { |a| [ a.created_at ] }.reverse[0..3]
            -if video_sub_category.videos_size_with_children > 4
              %p.others
                = link_to t('otherVideos') + video_sub_category.name, show_video_category_path(video_sub_category)


      =render 'shared/advert_xs'