app/src/config/routes.rb
Rails.application.routes.draw do

  concern :sluggable do
    collection do
      get 'slug'
    end
  end

  concern :commentable do
    member do
      post 'comment'
    end
  end

  resources :tags, only: :index do
    get :autocomplete, on: :collection
  end

  get 'ssearch' => "ssearch#index"

  resources :slides

  resources :contests, path: 'premio', concerns: :sluggable, except: [:show, :toggle_instagram_image,:index]
  get 'premio/:title/:image_id', to: 'contests#preview_instagram_image', as: :contest_image
  get 'premio/:title', to: 'contests#show', as: :show_contest
  get 'premio', to: 'contests#show'
  get 'contests/toggle_instagram_image/:image_id', to: 'contests#toggle_instagram_image'
  get 'contests', to: 'contests#index'

  resources :events, path: 'eventos', concerns: :sluggable

  resources :resorts, path: 'estacoes-ski-snowboard', concerns: :sluggable, except: :show

  get '/resorts/:id', to: 'resorts#resort_redirect', as: :resort_redirect
  get 'estacoes-ski-snowboard/:relation_id/:id', to: 'resorts#show', as: :show_resort

  get 'estacoes-ski-snowboard/:id', to: 'resort_categories#show', as: :show_resort_category
  resources :resort_categories, concerns: :sluggable, except: :show do
    get 'children', on: :member
  end

  get '/resorts', to: redirect('/estacoes-ski-snowboard')
  get '/resort_categories/:id', to: redirect('/estacoes-ski-snowboard/%{id}')

  resources :blogs

  resources :tips, path: 'dicas-de-snowboard', concerns: [:sluggable, :commentable], except: :show

  get '/tips/:id', to: 'tips#tip_redirect', as: :tip_redirect
  get 'dicas-de-snowboard/:category_id/:id', to: 'tips#show', as: :show_tip
  get 'dicas/:category_id/:id', to: redirect('tips#show')

  get 'dicas-de-snowboard/:id', to: 'tip_categories#show', as: :show_tip_category
  get 'dicas/:id', to: redirect('tip_categories#show')

  resources :tip_categories, concerns: :sluggable, except: :show
  get '/tips', to: redirect('/dicas-de-snowboard')
  get '/dicas', to: redirect('/dicas-de-snowboard')
  get '/tip_categories/:id', to: redirect('/dicas-de-snowboard/%{id}')

  resources :videos,  path: 'snowboard-videos', concerns: :sluggable, except: :show
  get 'snowboard-videos/:relation_id/:id', to: 'videos#show', as: :show_video

  get 'snowboard-videos/:id', to: 'video_categories#show', as: :show_video_category
  resources :video_categories, concerns: :sluggable, except: :show

  get '/video_categories/:id', to: redirect('/videos/%{id}')

  resources :breezes, :breeze_categories
  resources :image_galleries, :media_image_categories

  resources :accommodations, :tour_styles

  resources :tours, path: '/vamo-junto-snowboard', except: :show do
    get ':resort_country_id/:id', to: 'tours#show', as: :show_tour, on: :collection
    get 'search', on: :collection
    get ':slug', to: 'tours#index', on: :collection
    post 'comment', on: :member
    scope module: 'tours' do
      resources :participants do
        get 'recall', on: :member
      end
    end
  end
  resources :offers, path: '/pacotes-ski-snowboard', except: :show do
    get ':resort_country_id/:id', to: 'offers#show', as: :show_offer, on: :collection
    get 'search', on: :collection
    get ':slug', to: 'offers#index', on: :collection
    scope module: 'offers' do
      resources :participants
    end
  end

  root 'static_pages#index'

  get '/galera', to: 'static_pages#galera', path: '/contatos'
  get '/friends', to: 'static_pages#friends', path: '/amigos'
  get '/places', to: 'static_pages#places', path: '/lugares'
  get '/stickers', to: 'static_pages#stickers', path: '/adesivos'

  get 'users_controller/finish_signup'

  get '/discourse/sso', to: 'discourse#sso'
  get '/discourse/after_sign_in', to: 'discourse#after_sign_in'
  get '/discourse/logout', to: 'discourse#logout'

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    scope module: 'users' do
      resources :tours
      resources :offers
    end
  end
  scope '/manage' do
    resources :users do
      resources :image_galleries
      resources :notifications
      patch 'update_password', on: :collection
      resources :tours, module: 'manage'
    end
  end
  namespace :manage do
    resources :tours, concerns: :sluggable do
      scope module: 'tours' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end
    resources :offers, concerns: :sluggable do
      scope module: 'offers' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end

    resources :tags
  end

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/user' => 'users#profile', via: [:get], :as => :profile
  match '/user/full_sign_out' => 'users#full_sign_out', via: [:get], :as => :full_sign_out
  match '/athletes' => 'users#athletes', via: [:get], :as => :athletes, path: 'atletas-de-snowboard'
  match '/agencies' => 'offers#agencies', via: [:get], :as => :agencies, path: 'agencias-ski-snowboard'
  match '/organizations' => 'users#organizations', via: [:get], :as => :organizations, path: 'ogranizacoes-de-snowboard'

  get '/galera', to: redirect('contatos')
  get '/friends', to: redirect('amigos')
  get '/tours', to: redirect('vamo-junto-snowboard')
  get '/offers', to: redirect('pacotes-ski-snowboard')
  get '/athletes', to: redirect('atletas-de-snowboard')
  get '/agencies', to: redirect('agencias-ski-snowboard')
  get '/organizations', to: redirect('ogranizacoes-de-snowboard')

end

app/src/app/models/video.rb
# create_table :videos, force: true do |t|
#   t.string    :title
#   t.text      :description
#   t.integer   :source_cd
#   t.integer   :video_category_id
#   t.string    :source_link
#   t.timestamp :created_at,        precision: 6
#   t.timestamp :updated_at,        precision: 6
#   t.string    :slug
# end

class Video < ActiveRecord::Base
  include Slug
  slugged :title
  acts_as_taggable

  as_enum :source, youtube: 0, vimeo: 1
  belongs_to :video_category
  validates :title, presence: true
  validates :source_link, presence: true
end

app/src/app/controllers/videos_controller.rb
class VideosController < ApplicationController
  authorize_resource
  load_resource expect: :show

  before_action :load_show_resource, only: :show

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all.sort_by { |a| [ a.created_at ] }.reverse.paginate(:page => 1, :per_page => 15)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  def slug
    video = Video.new title: params[:title]
    render json: { slug: video.slug_preview }
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    respond_to do |format|
      if @video.save
        format.html { redirect_to show_video_path(@video.video_category, @video), notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|

      if @video.update(video_params)
        format.html { redirect_to show_video_path(@video.video_category, @video), notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def video_params
    params.require(:video).permit(:title, :slug, :source_cd, :source_link, :video_category_id, :description, :tag_list)
  end
end

app/src/app/helpers/videos_helper.rb
module VideosHelper
  def getYoutubeEmbedLink url
    id = extract_youtube_id(url)
    'http://www.youtube.com/embed/'+id+'?rel=0&autoplay=0'
  end

  def getVimeoEmbedLink url
    video_id = extract_vimeo_id(url)
    src = "//player.vimeo.com/video/#{video_id}"
    src
  end

  def thumbnail(url, options = {})
    if url =~ /youtube/
      youtube_thumbnail(url, options)
    else
      vimeo_thumbnail(url, options)
    end
  end

  def thumbnail_url(url, options = {})
    if url =~ /youtube/
      size = options[:size] ||= :high
      id = extract_youtube_id(url)
      "https://i.ytimg.com/vi/#{id}/#{YOUTUBE_FILES[size]}.jpg"
    else
      size = options[:size] ||= :large
      id = extract_vimeo_id(url)
      video_info=Vimeo::Simple::Video.info(id)
      video_info[0][VIMEO_FILES[size]]
    end
  end

  private

  def youtube_thumbnail(url, options = {})
    size = options[:size] ||= :high
    id = extract_youtube_id(url)
    image_tag("https://i.ytimg.com/vi/#{id}/#{YOUTUBE_FILES[size]}.jpg")
  end

  def vimeo_thumbnail(url, options = {})
    size = options[:size] ||= :large
    id = extract_vimeo_id(url)
    video_info = Vimeo::Simple::Video.info(id)
    image_tag(video_info[0][VIMEO_FILES[size]])
  end

  def extract_youtube_id(url)
    /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/.match(url)[2]
  end

  def extract_vimeo_id(url)
    /^.*(vimeo.com\/)([0-9].*)/.match(url)[2]
  end

  YOUTUBE_FILES = {
    default: 'default',
    medium: 'mqdefault',
    high: 'hqdefault',
    standard: 'sddefault',
    maxres: 'maxresdefault'
  }

  VIMEO_FILES = {
    small: 'thumbnail_small',
    medium: 'thumbnail_medium',
    large: 'thumbnail_large'
  }
end

app/src/app/views/videos/_form.html.haml
= form_for(@video, :html => {:mulvideoart => true, :class => 'admin-form'}) do |f|
  .actions
    = f.submit
  .field
    = f.label :title
    = f.text_field :title, data: { url: slug_videos_path }
  .field
    = f.label :slug
    = f.text_field :slug
  .field.tag_list
    = f.label :tag_list
    = f.text_field :tag_list
  .field
    = f.label :source
    = f.select :source, enum_option_pairs(Video, :source)
    .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :source_link
    = f.text_field :source_link
    -if @video.source_link.nil? || :source_link.empty?

      %iframe.youtube{:allowfullscreen => '', :frameborder => '0', :height => '315', :width => '560', :style => 'display:none'}

      %iframe.vimeo{:allowfullscreen => '', :frameborder => '0', :height => '315', :width => '560', :style => 'display:none'}

    -else
      - if @video.source_link.include?("youtube")
        %iframe.youtube{:allowfullscreen => '', :frameborder => '0', :height => '315', :src => getYoutubeEmbedLink(@video.source_link), :width => '560'}
      - else @video.source_link.include?("vimeo")
        %iframe.vimeo{:allowfullscreen => "", :frameborder => "0", :height => "281", :mozallowfullscreen => "", :src => getVimeoEmbedLink(@video.source_link), :width => "500"}

  .field
    = f.label :category
    = f.select(:video_category_id, nested_dropdown(VideoCategory.all.arrange))
  .actions
    = f.submit

app/src/app/views/videos/_video.html.haml
%li{:style=>"display: inline-block; vertical-align: middle; border-bottom: 0px solid #dbdbdb;"}
  .video-thumbnail[video]
    %p.video-thumbnail--name
      =link_to video.title[0..40], show_video_path(video.video_category, video)
    .video-thumbnail--image{:style=>"margin-left: 20px; margin-right: 20px;"}
      = link_to thumbnail(video.source_link), show_video_path(video.video_category, video)
  -if can? :video, :update
    = link_to 'Edit', edit_video_path(video)
  -if can? :video, :delete
    = link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' }
  .clear
  -#

app/src/app/views/videos/_video_xs.html.haml
%a.article.hidden-sm{:href => show_video_path(video_xs.video_category, video_xs)}
  .article--image-big
    =thumbnail(video_xs.source_link)
  .article--inner
    .article--title
      =video_xs.title
.article.visible-sm
  .article--inner.pad
    .article--image
      =thumbnail(video_xs.source_link)
    .article--info
      .article--title
        =video_xs.title
    .article--text
      =video_xs.description.html_safe
      %a{:href => show_video_path(video_xs.video_category, video_xs)}
        =t('Veja o video')
    .article--tools.visible-sm.clearfix

app/src/app/views/videos/edit.html.haml
%h2 Editing video
= render 'form'
= link_to 'Show', @video
|
\#{link_to 'Back', videos_path}

app/src/app/views/videos/index.html.haml
.main-content
  -content_for :for_head do
    -# general METAS
    %title Snowboard Videos | Zona Radical
    -# facebook METAS
    %meta{:property=>"og:type", :content =>"article"}
    %meta{:property=>"og:title", :content => "Zona Radical Snowboard Videos"}
    %meta{:property=>"og:url", :content => request.original_url.to_s}
    %meta{:property=> "og:image", :content=> "http://zonaradical.com.br/images/videos.png"}
    %meta{:property=> "og:description", :content=> "Acrescentamos no Zona Radical uma sessão de vídeos! Aprecie o que já deixamos para os fãs do snowboard. Conhece mais algum? Nos ajude a preencher a página!"}

  .heading
    %h1
      Snowboard Videos
      -# \:
      -# - unless VideoCategory.all.empty?
      -#  -VideoCategory.all.each do |video_category|
      -#    - if video_category.ancestry_depth==0
      -#      =link_to(video_category.name, main_app.video_category_path(video_category.id))
      -#      -if video_category !=VideoCategory.all.last
      -#        ,
  .clear


  %ul.stations-list
    %li
      Nos ajude a preencher a página!
      Conhece um vídeo irado?
      = mail_to('info@zonardical.com.br','Nos mande o link e adicionaremos!',:target=>"_newtab")
      .clear
    =render @videos
    -#= will_paginate @videos,:previous_label => '<<',:next_label => '>>', :inner_window => 1
  .clear


-content_for :aside do
  %aside
    = render 'shared/aside/aside_tags'
    =render 'shared/aside/aside_social_buttons'
    -# =render 'shared/aside/aside_video_category', :video_category => nil
    -# =render 'shared/aside/aside_fb_like_box'
    =render 'shared/aside/aside_advert'
    =render 'shared/aside/aside_resort_gallery'
  .clear

-content_for :for_mobile do
  =render 'layouts/header_xs', :header_txt=> nil, :header_url => nil

  .container
    .articles
      -# =render 'layouts/list_filters_xs', :header_txt => "Todas Dicas"
      .articles--title.clearfix
        .articles--filter.left
          %a.articles--filter-btn{:href => "#"} Categorias
          .articles--filter-box
            %ul.articles--filter-list
              =sub_menu_video_categories VideoCategory.all

        .news--item-title.right.clearfix
          .news--item-name.left
            =t('All Videos')

      .article
        .article--inner
          .article--desc
            Videos de Snowboard

      = render partial: "videos/video_xs", collection: @videos
      = will_paginate @videos

      =render 'shared/advert_xs'

app/src/app/views/videos/new.html.haml
%h2.admin-h2= t('newvideo')
= render 'form'
= link_to 'Back', videos_path

app/src/app/views/videos/show.html.haml
.main-content{:itemscope => true, :itemtype => "http://schema.org/VideoObject"}
  -content_for :for_head do
    -# general METAS
    %title Snowboard Videos: "#{@video.title} | Zona Radical
    -# facebook METAS
    %meta{:property=>"og:type", :content =>"website"}
    %meta{:name => "description", :content => @video.description.to_s}
    %meta{:property=>"og:title", :content => "Snowboard Videos: "+@video.title+" | Zona Radical"}
    %meta{:property=>"og:description", :content => @video.description.to_s}
    %meta{:property=>"og:url", :content => request.original_url.to_s}
    -# 'https://www.youtube.com/watch?v=lB8o_OWNCxw'}
    -#- if @video.source_link.include?("youtube")
    -#meta{:property=>"og:video:url", :content => getYoutubeEmbedLink(@video.source_link)}
    -#%meta{:property=>"og:video:secure_url", :content => getYoutubeEmbedLink(@video.source_link).gsub('http','https')}
    -# %meta{:property=>"og:video:url", :content => 'http://www.youtube.com/watch?v=lB8o_OWNCxw'}
    -# %meta{:property=>"og:video:secure_url", :content => 'https://www.youtube.com/watch?v=lB8o_OWNCxw'}
    -# %meta{:property=>"og:video", :content => @video.source_link}
    -#- elsif @video.source_link.include?("vimeo")
    -#  %meta{:property=>"og:video", :content => "http:"+getVimeoEmbedLink(@video.source_link)}
    -# %meta{:property=>"og:video", :content => @video.source_link}
    -# %meta{:property=>"og:video:type", :content => 'text/html'}
    -# %meta{:property=>"og:video:width", :content => '701'}
    -# %meta{:property=>"og:video:height", :content => '394'}
    -# second
    -# %meta{:property=>"og:video:url", :content => 'http://www.youtube.com/v/lB8o_OWNCxw?version=3&amp;autohide=1'}
    -# %meta{:property=>"og:video:secure_url", :content => 'https://www.youtube.com/v/lB8o_OWNCxw?version=3&amp;autohide=1'}
    -#%meta{:property=>"og:video:type", :content => 'application/x-shockwave-flash'}
    -#  %meta{:property=>"og:video:width", :content => '701'}
    -#  %meta{:property=>"og:video:height", :content => '394'}
    %meta{:property=>"og:image", :content =>thumbnail_url(@video.source_link).to_s}
    %meta{:itemprop=>"keywords", :content => @video.tag_list}
  -#request.original_url.to_s

  .heading
    %h1
      -#span{:itemprop=>"articleSection"}
      -# =t('videos')
      /\:
      %span{:itemprop=>"about"}
        -if @video.video_category.ancestry
          -#= link_to "Videos", "/videos/videos/", :class=>'video-header'
          />>
          - nums=Array.new(@video.video_category.ancestry_depth-1)
          - nums[0]=@video.video_category
          - (1..nums[0].ancestry_depth).each do |i|
            - nums[i]=nums[i-1].parent
          = nums.reverse.map{|wl| link_to wl.name, show_video_category_path(wl), :class=>'video-header'}.join(' >> ').html_safe
        -#= link_to @video.video_category.name,  show_video_category_path(@video.video_category), :class=>'video-header'



  %article
    %h3{:itemprop=>"name"}
      =@video.title
    %i= tag_list_linked(@video.tag_list)
    - if @video.source_link.include?("youtube")
      %iframe.youtube{:allowfullscreen => '', :frameborder => '0', :height => '394', :src => getYoutubeEmbedLink(@video.source_link), :width => '701'}
    - else @video.source_link.include?("vimeo")
      %iframe.youtube{:allowfullscreen => '', :frameborder => '0', :height => '394', :src => getVimeoEmbedLink(@video.source_link), :width => '701'}
    %p{:itemprop=>"description"}
      #{@video.description}
      = render 'shared/social_sharing', style: 'float: right;'
    - if can? :video, :update
      = link_to t('edit'), edit_video_path(@video)
      |
      \#{link_to 'Back', videos_path}
  .heading
-# end main-content

-content_for :aside do
  %aside
    =render 'shared/aside/aside_social_buttons'
    =#render 'shared/aside/aside_video_category', :video_category => @video.video_category
    =render 'shared/aside/aside_advert'
    =render 'shared/aside/aside_fb_like_box'
    =render 'shared/aside/aside_resort_gallery'
  .clear


-content_for :for_mobile do
  =render 'layouts/header_xs', :header_txt=> @video.video_category.name, :header_url => show_video_category_path(@video.video_category)


  .container
    .articles
      -# =render 'layouts/list_filters_xs', :header_txt => "Todas Dicas"
      .articles--title.clearfix
        .articles--filter.left
          %a.articles--filter-btn{:href => "#"} Categorias
          .articles--filter-box
            %ul.articles--filter-list
              =sub_menu_video_categories VideoCategory.all

        .news--item-title.right.clearfix
          .news--item-name.left
            =@video.title

      .article
        .article--inner
          .article--desc
            #{@video.description}

    - if @video.source_link.include?("youtube")
      %iframe.youtube{:allowfullscreen => '', :frameborder => '0',  :src => getYoutubeEmbedLink(@video.source_link), :width => '100%'}
    - else @video.source_link.include?("vimeo")
      %iframe.youtube{:allowfullscreen => '', :frameborder => '0',  :src => getVimeoEmbedLink(@video.source_link), :width => '100%'}
    = render 'shared/social_sharing', style: 'float: right;'

    =render 'shared/advert_xs'