app/src/config/routes.rb
Rails.application.routes.draw do

  concern :sluggable do
    collection do
      get 'slug'
    end
  end

  concern :commentable do
    member do
      post 'comment'
    end
  end

  resources :tags, only: :index do
    get :autocomplete, on: :collection
  end

  get 'ssearch' => "ssearch#index"

  resources :slides

  resources :contests, path: 'premio', concerns: :sluggable, except: [:show, :toggle_instagram_image,:index]
  get 'premio/:title/:image_id', to: 'contests#preview_instagram_image', as: :contest_image
  get 'premio/:title', to: 'contests#show', as: :show_contest
  get 'premio', to: 'contests#show'
  get 'contests/toggle_instagram_image/:image_id', to: 'contests#toggle_instagram_image'
  get 'contests', to: 'contests#index'

  resources :events, path: 'eventos', concerns: :sluggable

  resources :resorts, path: 'estacoes-ski-snowboard', concerns: :sluggable, except: :show

  get '/resorts/:id', to: 'resorts#resort_redirect', as: :resort_redirect
  get 'estacoes-ski-snowboard/:relation_id/:id', to: 'resorts#show', as: :show_resort

  get 'estacoes-ski-snowboard/:id', to: 'resort_categories#show', as: :show_resort_category
  resources :resort_categories, concerns: :sluggable, except: :show do
    get 'children', on: :member
  end

  get '/resorts', to: redirect('/estacoes-ski-snowboard')
  get '/resort_categories/:id', to: redirect('/estacoes-ski-snowboard/%{id}')

  resources :blogs

  resources :tips, path: 'dicas-de-snowboard', concerns: [:sluggable, :commentable], except: :show

  get '/tips/:id', to: 'tips#tip_redirect', as: :tip_redirect
  get 'dicas-de-snowboard/:category_id/:id', to: 'tips#show', as: :show_tip
  get 'dicas/:category_id/:id', to: redirect('tips#show')

  get 'dicas-de-snowboard/:id', to: 'tip_categories#show', as: :show_tip_category
  get 'dicas/:id', to: redirect('tip_categories#show')

  resources :tip_categories, concerns: :sluggable, except: :show
  get '/tips', to: redirect('/dicas-de-snowboard')
  get '/dicas', to: redirect('/dicas-de-snowboard')
  get '/tip_categories/:id', to: redirect('/dicas-de-snowboard/%{id}')

  resources :videos,  path: 'snowboard-videos', concerns: :sluggable, except: :show
  get 'snowboard-videos/:relation_id/:id', to: 'videos#show', as: :show_video

  get 'snowboard-videos/:id', to: 'video_categories#show', as: :show_video_category
  resources :video_categories, concerns: :sluggable, except: :show

  get '/video_categories/:id', to: redirect('/videos/%{id}')

  resources :breezes, :breeze_categories
  resources :image_galleries, :media_image_categories

  resources :accommodations, :tour_styles

  resources :tours, path: '/vamo-junto-snowboard', except: :show do
    get ':resort_country_id/:id', to: 'tours#show', as: :show_tour, on: :collection
    get 'search', on: :collection
    get ':slug', to: 'tours#index', on: :collection
    post 'comment', on: :member
    scope module: 'tours' do
      resources :participants do
        get 'recall', on: :member
      end
    end
  end
  resources :offers, path: '/pacotes-ski-snowboard', except: :show do
    get ':resort_country_id/:id', to: 'offers#show', as: :show_offer, on: :collection
    get 'search', on: :collection
    get ':slug', to: 'offers#index', on: :collection
    scope module: 'offers' do
      resources :participants
    end
  end

  root 'static_pages#index'

  get '/galera', to: 'static_pages#galera', path: '/contatos'
  get '/friends', to: 'static_pages#friends', path: '/amigos'
  get '/places', to: 'static_pages#places', path: '/lugares'
  get '/stickers', to: 'static_pages#stickers', path: '/adesivos'

  get 'users_controller/finish_signup'

  get '/discourse/sso', to: 'discourse#sso'
  get '/discourse/after_sign_in', to: 'discourse#after_sign_in'
  get '/discourse/logout', to: 'discourse#logout'

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    scope module: 'users' do
      resources :tours
      resources :offers
    end
  end
  scope '/manage' do
    resources :users do
      resources :image_galleries
      resources :notifications
      patch 'update_password', on: :collection
      resources :tours, module: 'manage'
    end
  end
  namespace :manage do
    resources :tours, concerns: :sluggable do
      scope module: 'tours' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end
    resources :offers, concerns: :sluggable do
      scope module: 'offers' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end

    resources :tags
  end

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/user' => 'users#profile', via: [:get], :as => :profile
  match '/user/full_sign_out' => 'users#full_sign_out', via: [:get], :as => :full_sign_out
  match '/athletes' => 'users#athletes', via: [:get], :as => :athletes, path: 'atletas-de-snowboard'
  match '/agencies' => 'offers#agencies', via: [:get], :as => :agencies, path: 'agencias-ski-snowboard'
  match '/organizations' => 'users#organizations', via: [:get], :as => :organizations, path: 'ogranizacoes-de-snowboard'

  get '/galera', to: redirect('contatos')
  get '/friends', to: redirect('amigos')
  get '/tours', to: redirect('vamo-junto-snowboard')
  get '/offers', to: redirect('pacotes-ski-snowboard')
  get '/athletes', to: redirect('atletas-de-snowboard')
  get '/agencies', to: redirect('agencias-ski-snowboard')
  get '/organizations', to: redirect('ogranizacoes-de-snowboard')

end

app/src/app/models/media_image_category.rb
# create_table :media_image_categories, force: true do |t|
#   t.string    :name
#   t.text      :description
#   t.string    :ancestry
#   t.string    :index
#   t.integer   :ancestry_depth,               default: 0
#   t.timestamp :created_at,     precision: 6
#   t.timestamp :updated_at,     precision: 6
#   t.string    :image
# end

class MediaImageCategory < ActiveRecord::Base
  has_ancestry( :cache_depth => true )

  validates :name, presence: true
  has_many :image_galleries, as: :image_gallerable
  mount_uploader :image, CategoryImageUploader

end

app/src/app/controllers/media_image_categories_controller.rb
class MediaImageCategoriesController < ApplicationController
  load_and_authorize_resource

  # GET /media_image_categories
  # GET /media_image_categories.json
  def index
    @media_image_categories = MediaImageCategory.all
  end

  # GET /media_image_categories/1
  # GET /media_image_categories/1.json
  def show
    @image_galleries = @media_image_category.image_galleries.page(params[:page])
  end

  # GET /media_image_categories/new
  def new
    @media_image_category = MediaImageCategory.new
  end

  # GET /media_image_categories/1/edit
  def edit
  end

  # POST /media_image_categories
  # POST /media_image_categories.json
  def create
    @media_image_category = MediaImageCategory.new(media_image_category_params)

    respond_to do |format|
      if @media_image_category.save
        format.html { redirect_to @media_image_category, notice: 'MediaImage category was successfully created.' }
        format.json { render :show, status: :created, location: @media_image_category }
      else
        format.html { render :new }
        format.json { render json: @media_image_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media_image_categories/1
  # PATCH/PUT /media_image_categories/1.json
  def update
    respond_to do |format|
      if @media_image_category.update(media_image_category_params)
        format.html { redirect_to @media_image_category, notice: 'MediaImage category was successfully updated.' }
        format.json { render :show, status: :ok, location: @media_image_category }
      else
        format.html { render :edit }
        format.json { render json: @media_image_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media_image_categories/1
  # DELETE /media_image_categories/1.json
  def destroy
    @media_image_category.destroy
    respond_to do |format|
      format.html { redirect_to media_image_categories_url, notice: 'MediaImage category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def media_image_category_params
    params.require(:media_image_category).permit(:name, :parent_id, :description, :image)
  end
end

app/src/app/views/media_image_categories/_form.html.haml
= form_for @media_image_category do |f|
  - if @media_image_category.errors.any?
    #error_explanation
      %h1= "#{pluralize(@media_image_category.errors.count, "error")} prohibited this tip_category from being saved:"
      %ul
        - @media_image_category.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :parent_id, t('parent')
    = f.collection_select(:parent_id, MediaImageCategory.all,:id, :name,{:prompt => t('selectParent')})
  .field
    = f.label :description
    = f.text_area :description,:class => 'froala', :rows => 40, :cols => 120
  .field
    = image_tag @media_image_category.image_url(:thumb_1200_630).to_s
    = f.label :image
    = f.file_field :image
    = f.check_box :remove_image

  .actions
    = f.submit 'Save'

app/src/app/views/media_image_categories/_media_image_category.html.haml
%li.media_image_category
  .details
    %p.name
      = link_to media_image_category.name, media_image_category_path(media_image_category)
    %p= truncate( media_image_category.description, length: 200)
  .clear
  - if can? :media_image_category, :update, :destroy
    .control
      = link_to t('edit'), edit_media_image_category_path(media_image_category)
      = link_to 'Destroy', media_image_category, method: :delete, data: { confirm: 'Are you sure?' }

app/src/app/views/media_image_categories/edit.html.haml
%h2 Editing tip_category

= render 'form'

= link_to 'Show', @tip_category
\|
= link_to 'Back', tip_categories_path

app/src/app/views/media_image_categories/index.html.haml
.main-content
  .heading
  -if can? MediaImageCategory, :create
    = link_to 'New Media category', new_media_image_category_path
  .clear
  %ul.media_image_category_list
    =nested_categories @media_image_categories.arrange
.clear

app/src/app/views/media_image_categories/new.html.haml
%h1=t('newTipCategory')

= render 'form'

= link_to 'Back', tip_categories_path

app/src/app/views/media_image_categories/show.html.haml
%p#notice= notice
.main-content
  .heading
    %h1= t('Media') + ': ' + @media_image_category.name
  .introtext= @media_image_category.description.html_safe unless @media_image_category.description.nil?
  -if can? :update, @media_image_category
    = link_to t('edit'), edit_tip_category_path(@media_image_category)
  .clear
  %ul.stations-list
    =render @image_galleries
    = will_paginate @image_galleries,:previous_label => '<<',:next_label => '>>', :inner_window => 1
  -if @media_image_category.children?
    -@media_image_category.children.each do |media_category|
      -unless media_category.tips.empty?
        .heading
          %h1= media_category.name + ' (' + media_category.tips.size.to_s + ')'
        .introtext= media_category.description.html_safe unless media_category.description.nil?
        -if can? :update, media_category
          = link_to t('edit'), edit_media_image_category_path(media_category)
        .clear
        %ul.stations-list
          =render media_category.tips.limit(3)
        -if media_category.tips.size > 3
          %p= link_to t('otherTips') + media_category.name, media_image_category_path(media_category)
-content_for :aside do
  %aside
    =render 'shared/aside/aside_social_buttons'
    =#render 'shared/aside/aside_tip_category', :tip_category => @media_image_category
    =render 'shared/aside/aside_advert'
    =render 'shared/aside/aside_fb_like_box'
    =render 'shared/aside/aside_resort_gallery'
  .clear