app/src/config/routes.rb
Rails.application.routes.draw do

  concern :sluggable do
    collection do
      get 'slug'
    end
  end

  concern :commentable do
    member do
      post 'comment'
    end
  end

  resources :tags, only: :index do
    get :autocomplete, on: :collection
  end

  get 'ssearch' => "ssearch#index"

  resources :slides

  resources :contests, path: 'premio', concerns: :sluggable, except: [:show, :toggle_instagram_image,:index]
  get 'premio/:title/:image_id', to: 'contests#preview_instagram_image', as: :contest_image
  get 'premio/:title', to: 'contests#show', as: :show_contest
  get 'premio', to: 'contests#show'
  get 'contests/toggle_instagram_image/:image_id', to: 'contests#toggle_instagram_image'
  get 'contests', to: 'contests#index'

  resources :events, path: 'eventos', concerns: :sluggable

  resources :resorts, path: 'estacoes-ski-snowboard', concerns: :sluggable, except: :show

  get '/resorts/:id', to: 'resorts#resort_redirect', as: :resort_redirect
  get 'estacoes-ski-snowboard/:relation_id/:id', to: 'resorts#show', as: :show_resort

  get 'estacoes-ski-snowboard/:id', to: 'resort_categories#show', as: :show_resort_category
  resources :resort_categories, concerns: :sluggable, except: :show do
    get 'children', on: :member
  end

  get '/resorts', to: redirect('/estacoes-ski-snowboard')
  get '/resort_categories/:id', to: redirect('/estacoes-ski-snowboard/%{id}')

  resources :blogs

  resources :tips, path: 'dicas-de-snowboard', concerns: [:sluggable, :commentable], except: :show

  get '/tips/:id', to: 'tips#tip_redirect', as: :tip_redirect
  get 'dicas-de-snowboard/:category_id/:id', to: 'tips#show', as: :show_tip
  get 'dicas/:category_id/:id', to: redirect('tips#show')

  get 'dicas-de-snowboard/:id', to: 'tip_categories#show', as: :show_tip_category
  get 'dicas/:id', to: redirect('tip_categories#show')

  resources :tip_categories, concerns: :sluggable, except: :show
  get '/tips', to: redirect('/dicas-de-snowboard')
  get '/dicas', to: redirect('/dicas-de-snowboard')
  get '/tip_categories/:id', to: redirect('/dicas-de-snowboard/%{id}')

  resources :videos,  path: 'snowboard-videos', concerns: :sluggable, except: :show
  get 'snowboard-videos/:relation_id/:id', to: 'videos#show', as: :show_video

  get 'snowboard-videos/:id', to: 'video_categories#show', as: :show_video_category
  resources :video_categories, concerns: :sluggable, except: :show

  get '/video_categories/:id', to: redirect('/videos/%{id}')

  resources :breezes, :breeze_categories
  resources :image_galleries, :media_image_categories

  resources :accommodations, :tour_styles

  resources :tours, path: '/vamo-junto-snowboard', except: :show do
    get ':resort_country_id/:id', to: 'tours#show', as: :show_tour, on: :collection
    get 'search', on: :collection
    get ':slug', to: 'tours#index', on: :collection
    post 'comment', on: :member
    scope module: 'tours' do
      resources :participants do
        get 'recall', on: :member
      end
    end
  end
  resources :offers, path: '/pacotes-ski-snowboard', except: :show do
    get ':resort_country_id/:id', to: 'offers#show', as: :show_offer, on: :collection
    get 'search', on: :collection
    get ':slug', to: 'offers#index', on: :collection
    scope module: 'offers' do
      resources :participants
    end
  end

  root 'static_pages#index'

  get '/galera', to: 'static_pages#galera', path: '/contatos'
  get '/friends', to: 'static_pages#friends', path: '/amigos'
  get '/places', to: 'static_pages#places', path: '/lugares'
  get '/stickers', to: 'static_pages#stickers', path: '/adesivos'

  get 'users_controller/finish_signup'

  get '/discourse/sso', to: 'discourse#sso'
  get '/discourse/after_sign_in', to: 'discourse#after_sign_in'
  get '/discourse/logout', to: 'discourse#logout'

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    scope module: 'users' do
      resources :tours
      resources :offers
    end
  end
  scope '/manage' do
    resources :users do
      resources :image_galleries
      resources :notifications
      patch 'update_password', on: :collection
      resources :tours, module: 'manage'
    end
  end
  namespace :manage do
    resources :tours, concerns: :sluggable do
      scope module: 'tours' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end
    resources :offers, concerns: :sluggable do
      scope module: 'offers' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end

    resources :tags
  end

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/user' => 'users#profile', via: [:get], :as => :profile
  match '/user/full_sign_out' => 'users#full_sign_out', via: [:get], :as => :full_sign_out
  match '/athletes' => 'users#athletes', via: [:get], :as => :athletes, path: 'atletas-de-snowboard'
  match '/agencies' => 'offers#agencies', via: [:get], :as => :agencies, path: 'agencias-ski-snowboard'
  match '/organizations' => 'users#organizations', via: [:get], :as => :organizations, path: 'ogranizacoes-de-snowboard'

  get '/galera', to: redirect('contatos')
  get '/friends', to: redirect('amigos')
  get '/tours', to: redirect('vamo-junto-snowboard')
  get '/offers', to: redirect('pacotes-ski-snowboard')
  get '/athletes', to: redirect('atletas-de-snowboard')
  get '/agencies', to: redirect('agencias-ski-snowboard')
  get '/organizations', to: redirect('ogranizacoes-de-snowboard')

end

app/src/app/views/shared/aside/_aside_advert.haml
-#.advert-block
-#  -#-if rand(10)<4
-#  -#  .heading
-# .heading
-#   %h5 Melhores Trips
-# = link_to image_tag('event-rtn.jpg', :alt=>"Uma trip de amigos para Colorado 2017"), "http://zonaradical.com.br/pacotes-ski-snowboard/Breckenridge/colorado-eua-2017", :target=> "blank"

.advert-block
  -#-if rand(10)<4
  -#  .heading
  .heading
    %h5 Adesivos do ZR a um clique
  = link_to image_tag('event-pedido.jpg'), main_app.stickers_path, :target=> "blank"
  -#-else
  -#  .heading
  -#    %h5 Proximo Evento
  -#  = image_tag("/images/22-cbdn-adv.png", :alt=>"Campeonato Brasileiro de Snowboard 2016")

-#.advert-block
-#  .heading
-#    %h5 Ofertas
-#  -if rand(10)<6
-#    = link_to image_tag("/images/offer-valfredo.png", :alt=>"Disconto especial da Agencia Turismo em Chile"), "http://zonaradical.com.br/users/agencia-turismoemchile", :target=> "blank"
-#  -else
-#    = link_to image_tag("/images/offer-overtravel.jpg", :alt=>"Disconto especial da Agencia OverTravel360"), "http://zonaradical.com.br/users/operadora-overtravel360-com", :target=> "blank"

app/src/app/views/shared/aside/_aside_fb_like_box.html.haml
.heading
  %h5 Facebook
.fb-like-box{"data-colorscheme" => "light", "data-header" => "true", "data-href" => "https://www.facebook.com/zonaradicalbrasil", "data-show-border" => "true", "data-show-faces" => "true", "data-stream" => "false", "data-width" => "303", :style => "padding-bottom: 40px;"}

app/src/app/views/shared/aside/_aside_latest_blogs.html.haml
.heading
  %h5 Ultimos Blogs no ZR
  %a.all{:href => blogs_path} Todos
%ul.places-list
  - @blogs[0..1].each do |blg|
    %li
      %a{:href => blog_path(blg)}
        %img{:alt => blg.title, :src => blg.image_url(:thumb)}/
        =blg.title

app/src/app/views/shared/aside/_aside_resort_category.html.haml
.heading
  %h5=t('resorts')
%ul.categories
  %li
    =link_to resorts_path, :rel => 'nofollow' do
      All ( #{Resort.all.size.to_s} )

  -if !resort_category.nil?
    %li
      =aside_resort_categories resort_category
    -ResortCategory.roots.each do |root_category|
      -if resort_category.root != root_category
        %li
          %span.active=link_to root_category.name, show_resort_category_path(root_category)
  -else
    -ResortCategory.roots.each do |root_category|
      %li
        =link_to root_category.name, show_resort_category_path(root_category)

app/src/app/views/shared/aside/_aside_resort_gallery.html.haml
.heading
  %h5 Lugares: Valle Nevado
  %a.all{:href => '#'} Tudo
%ul.places-list
  %li
    %a{:href => '#'}
      %img{:alt => '', :src => '/images/places-1.jpg'}/
      Title 1
  %li
    %a{:href => '#'}
      %img{:alt => '', :src => '/images/places-2.jpg'}/
      Title 2

app/src/app/views/shared/aside/_aside_share_buttons.html.haml
.heading
  %h5 Compartilhe
= render 'shared/social_sharing', style: 'float: left; margin-bottom: 30px;'
.clear

app/src/app/views/shared/aside/_aside_sn_forecast.haml
.advert-block
  .heading
    %h5 Snow-Forecast
  %link{:href => "http://www.snow-forecast.com/stylesheets/feed.css", :media => "screen", :rel => "stylesheet", :type => "text/css"}/
  #wf-weatherfeed
    %iframe{:allowtransparency => "true", :frameborder => "0", :height => "272", :marginheight => "0", :marginwidth => "0", :scrolling => "no", :src => "http://www.snow-forecast.com/resorts/"+resort_id+"/forecasts/feed/mid/m", :style => "overflow:hidden;border:none;", :width => "469"}
      %p Your browser does not support iframes.
    #wf-link
      %a{:href => "http://www.snow-forecast.com/"}
        %img{:alt => "Snow Forecast", :src => "http://www.snow-forecast.com/images/feed/snowlogo-150.png"}/
      %p#cmt
        View detailed snow forecast for
        %a{:href => "http://www.snow-forecast.com/resorts/"+resort_id+"?utm_source=embeddable&amp;utm_medium=widget&amp;utm_campaign="+resort_id} #{resort_id}
        at:
        %br/
        %a{:href => "http://www.snow-forecast.com/resorts/"+resort_id+"?utm_source=embeddable&amp;utm_medium=widget&amp;utm_campaign="+resort_id}
          %strong snow-forecast.com
      %div{:style => "clear: both;"}

app/src/app/views/shared/aside/_aside_social_buttons.html.haml
.heading
  %h5 Fique conectado
%ul.social-buttons
  %li
    %a.fb{:href => "https://www.facebook.com/zonaradicalbrasil", :target => "_blank"}
  %li
    %a.yt{:href => "http://instagram.com/zonaradicalbr", :target => "_blank"}
  %li
    %a.tw{:href => "https://twitter.com/ZonaRadicalBR", :target => "_blank"}
  %li
    %a.gp{:href => "https://www.youtube.com/channel/UCSrETbpCKUUOS-RBhKZYfRw", :target => "_blank"}
  %li
    -#a.rss{:href => Rails.application.secrets.discourse_url + '/session/sso?return_path='+Rails.application.secrets.discourse_url+'/categories', :alt=> "Comunidade ZR"}

app/src/app/views/shared/aside/_aside_tags.html.haml
.heading
  %h5 Tags
%div.tag_cloud
  - tag_cloud Tag.used, %w{s m l} do |tag, css_class|
    =link_to tag.name, tags_path(tag_list: tag.name), class: css_class

app/src/app/views/shared/aside/_aside_tip_category.html.haml
.heading
  %h5= t('categories')
%ul.categories
  %li
    =link_to tips_path, :rel => 'nofollow' do
      All
      %span='(' + Tip.all.size.to_s + ')'
    -TipCategory.all.each do |root_category|
      %li
        =link_to root_category.name, show_tip_category_path(root_category)

app/src/app/views/shared/aside/_contest_leader.html.haml
-unless @instagram_images.empty?
  .heading
    %h5 Contest leaders
  %ul.contest-leaders
    %li
      =link_to image_tag(@instagram_images[0].thumb_url), contests_path,{'title' => "#{@instagram_images[0].username}(#{@instagram_images[0].full_name}): #{@instagram_images[0].caption}", 'id' => "instagram_image_#{@instagram_images[0].id}"}
    %li
      =link_to image_tag(@instagram_images[1].thumb_url), contests_path,{'title' => "#{@instagram_images[1].username}(#{@instagram_images[1].full_name}): #{@instagram_images[1].caption}", 'id' => "instagram_image_#{@instagram_images[1].id}"}
    %li
      =link_to image_tag(@instagram_images[2].thumb_url), contests_path,{'title' => "#{@instagram_images[2].username}(#{@instagram_images[2].full_name}): #{@instagram_images[2].caption}", 'id' => "instagram_image_#{@instagram_images[2].id}"}